<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>New CategoryOfDish</title>
    <link rel="stylesheet" href="css/styles.css"></link>

    <style>
        body {
            background-color: #faf0e6;
            margin: auto;
        }

        a {
            text-decoration: none;
            color: rgba(134, 134, 200, 1);

        }
        a:hover {
            color: #dd4192;
        }

        tbody {
            font-size: 1.2rem;
        }

    </style>
</head>
<body>

<br>
<br>
<br>
<br>
<h1 align ="center">Ваш заказ оформлен!</h1>
<br>
<h2 align ="center">
    <a href="/">Ок</a>
</h2>

</body>
</html>