<html>
<head>
    <title>Registration</title>
</head>
<body>
<form action="/registration" method="post">
    Имя<input type="text" name="name"><br>
    Фамилия<input type="text" name="surName"><br>
    NickName<input type="text" name="nickName"><br>
    Password<input type="password" name="password"><br>
<!--    День рождения<input type="" name="birthday"><br>-->
    Пол<input type="text" name="gender"><br>
    <input type="submit" value="Create!">
</form>
</body>
</html>