<!DOCTYPE html>
<html>
<head>
    <title>Registration</title>
</head>
<body>
<form action="/registration" method="post">
    Имя<input type="text" name="name"><br>
    Фамилия<input type="text" name="surName"><br>
    Login<input type="text" name="login"><br>
    Password<input type="password" name="password"><br>
    День рождения<input type="date" name="day"><br>
    <input type="submit" value="Create!">
</form>
</body>
</html>